name: Docker Image CI

on:
  push:
    tags:
      - 'v*'

jobs:
  docker-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        
      - uses: crazy-max/ghaction-docker-meta@v1
        name: Docker meta
        id: docker_meta
        with:
          images: aoikazto/aswcloud-server
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx
        
      - uses: docker/login-action@v1
        name: Login to DockerHub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v2
        name: Build and push
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  deploy:
    needs: docker-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          # Optionally strip `v` prefix
          strip_v: true

      - name: Use tag
        run: echo ${{steps.tag.outputs.tag}}
        

      - uses: actions/checkout@v2
        name: Checkout
        with:
          repository: aswcloud/argo-cd
          # 다른 저장소에 push 하려면 Personal Access Token이 필요.
          ref: main
          token: ${{ secrets.BOT_TOKEN }}

      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          repository: aswcloud/argo-cd
          token: ${{ secrets.BOT_TOKEN }}
          valueFile: 'servercomm/deployment-aswcloud.yaml'
          propertyPath: 'spec.template.spec.containers[0].image'
          value: aoikazto/aswcloud-server:${{steps.tag.outputs.tag}}
          commitChange: false
          updateFile: true
          workDir: .
      
      - name: Add & Commit
        uses: EndBug/add-and-commit@v4.4.0
        with:
          add: '.'
          ref: "main"
          author_name: 'Piorosen-Bot'
          author_email: 'ckwngud1@gmail.com'
          message: ${{ github.event.head_commit.message }}
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          
      - name: Push commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
          repository: aswcloud/argo-cd
          branch: main

